### ISSUE TITLE
Doesn't seem to work for me

### ISSUE THREAD

**Issue by durkovich** [Volkanite/TestSpoof#4]
Just ran the .exe and was still unable to run Rust with EAC in test mode. I really appreciate your work on this and would love to get it working!

**Comment by Volkanite** [comment]
EAC was updated to get around this and i never had the time to update it. A better solution would be https://github.com/hfiref0x/DSEFix. Using DSEFix, you won't even have to boot into test mode as it allows you to load unsigned drivers in normal mode.

**Comment by durkovich** [comment]
awesome, thanks!
